# Generated by Django 3.0.2 on 2022-07-14 13:07

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('file_url', models.FileField(upload_to=app.models.file_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image_url', models.ImageField(upload_to=app.models.img_upload_to)),
                ('order', models.TextField()),
                ('family', models.TextField()),
                ('status', models.TextField()),
                ('distribution', models.TextField()),
                ('habitat', models.TextField(blank=True, null=True)),
                ('population', models.TextField(blank=True, null=True)),
                ('protection', models.TextField(blank=True, null=True)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Classification')),
            ],
        ),
    ]
